print("hi this game will be very easy")
print("or not so easy")
print("heehaa hahahahahahaha aaaaeeeehahaha")
print("dont buy dinobots until im finished but g1 i will tell you in another proj when im done")
print("snarl a stegousaurus")
print("slag a triceratops")
print("sludge a brontosourus")
print("swoop a teridactyl")
print("grimlock the t rex and the leader of g1")
print("want more?  extra: slasher a vilociraptor you can call him slash ")
print("if you collect all five sometimes slasher you  can make CHINGBOR and he is INSANE but what about volcaniucus collect only five")
print(" links:amazon,etsy,daraz")
print("bye friends hope you had fun!")